version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
      - ./mysql/data:/var/lib/mysql
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
