version: '3'

services:
  nginx:
    image: nginx:1.16.1
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - ./nginx/default.conf.template:/etc/nginx/conf.d/default.conf.template
    env_file:
      - ./.env
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"

  trycatch:
    image: node:12.13.0
    container_name: trycatch
    volumes:
      - ./:/app/
    working_dir: /app/server/
    user: root
    command: bash -c "npm install yarn pm2 -g && yarn install && yarn workspace client build && pm2-runtime bin/www"
    restart: always
    env_file:
      - ./.env

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./mysql.cnf:/etc/mysql/conf.d/custom.cnf
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    env_file:
      - ./.env
    ports:
      - '3306:3306'
