const INPUT_TAG = 'input';
const BROWSER_COPY_COMMAND = 'copy';
const ENTER_KEYCODE = 13;
const LOCALSTORAGE_NICKNAME_KEY = 'trycatch-nickname';

export {
  INPUT_TAG,
  BROWSER_COPY_COMMAND,
  ENTER_KEYCODE,
  LOCALSTORAGE_NICKNAME_KEY,
};
