const PURE_WHITE_COLOR = '#ffffff';
const BASE_WHITE_COLOR = '#EFEFF1';
const BASE_BLACK_COLOR = '#000000';
const THEME_COLOR = '#5A96FF';
const THEME_HOVER_COLOR = '#3C83FF';
const THEME_BORDER_COLOR = '#005DFD';
const PANEL_COLOR = '#FFFFFF';
const BACKGROUND_COLOR = '#E5F1FF';
const STREAMER_BORDER_COLOR = '#E74C3C';
const SKELETON_COMPONENT_COLOR = '#DFE4EA';
const SKELETON_HIGHLIGHT_COLOR = '#F1F2F6';
const LOADING_DOT_COLOR = '#636e72';
const INFORMATION_COLOR = '#FF0000';

export default {
  PURE_WHITE_COLOR,
  BASE_WHITE_COLOR,
  BASE_BLACK_COLOR,
  THEME_COLOR,
  THEME_HOVER_COLOR,
  THEME_BORDER_COLOR,
  PANEL_COLOR,
  BACKGROUND_COLOR,
  STREAMER_BORDER_COLOR,
  SKELETON_COMPONENT_COLOR,
  SKELETON_HIGHLIGHT_COLOR,
  LOADING_DOT_COLOR,
  INFORMATION_COLOR,
};
