const ONE_SECOND = 1000;
const DEFAULT_INACTIVE_PLAYER_BAN_TIME = 20;
const PRIVATE_ROOM_INACTIVE_PLAYER_BAN_TIME = 300;
const PRIVATE_ROOM_INACTIVE_PLAYER_BAN_TIME_IN_MINUTE =
  PRIVATE_ROOM_INACTIVE_PLAYER_BAN_TIME / 60;
const CLIPBOARD_COPY_MESSAGE_DURATION = 1;
export {
  ONE_SECOND,
  DEFAULT_INACTIVE_PLAYER_BAN_TIME,
  PRIVATE_ROOM_INACTIVE_PLAYER_BAN_TIME,
  PRIVATE_ROOM_INACTIVE_PLAYER_BAN_TIME_IN_MINUTE,
  CLIPBOARD_COPY_MESSAGE_DURATION,
};
