module.exports = {
  INITIAL_ROUND: 1,
  MIN_PLAYER_COUNT: 2,
  MAX_PLAYER_COUNT: 4,
  ONE_SET_SECONDS: 80,
  MAX_ROUND_NUMBER: 3,
  ONE_SECOND: 1000,
  MAX_QUIZ_SELECTION_WAITING_TIME: 10,
  MAX_PEER_CONNECTION_WAITING_TIME: 10000,
};
