const STYLE_COLORS = {
  PURE_WHITE_COLOR: '#ffffff',
  BASE_WHITE_COLOR: '#EFEFF1',
  BASE_BLACK_COLOR: '#000000',
  THEME_COLOR: '#5A96FF',
  THEME_HOVER_COLOR: '#3C83FF',
  PANEL_COLOR: '#FFFFFF',
  BACKGROUND_COLOR: '#E5F1FF',
};

export default STYLE_COLORS;
