const STYLE_COLORS = {
  WHITE_COLOR: '#FFFFFF',
  THEME_COLOR: '#6C19E8',
  BUTTON_BACKGROUND_COLOR: '#6C19E8',
  BUTTON_BACKGROUND_COLOR_HOVER: '#9147FF',
  PANEL_BACKGROUND_COLOR: '#17171A',
  PLAYER_PROFILE_BACKGROUND_COLOR: '#000000',
  GAME_PAGE_BACKGROUND_COLOR: '#3A3A3C',
  HEADER_BACKGROUND_COLOR: '#000000',
  READY_STATUS_BORDER_COLOR: '#9147FF',
  INPUT_DEFAULT_UNDERLINE_COLOR: '#000000',
};

export default STYLE_COLORS;
