const STYLE_COLORS = {
  PURE_WHITE_COLOR: '#ffffff',
  BASE_WHITE_COLOR: '#EFEFF1',
  BASE_BLACK_COLOR: '#000000',
  THEME_COLOR: '#5A96FF',
  THEME_HOVER_COLOR: '#3C83FF',
  THEME_BORDER_COLOR: '#005DFD',
  PANEL_COLOR: '#FFFFFF',
  BACKGROUND_COLOR: '#E5F1FF',
  STREAMER_BORDER_COLOR: '#E74C3C',
  SKELETON_COMPONENT_COLOR: '#DFE4EA',
  SKELETON_HIGHLIGHT_COLOR: '#F1F2F6',
  LOADING_DOT_COLOR: '#636e72',
  INFORMATION_COLOR: '#FF0000',
};

export default STYLE_COLORS;
