const DATABASE = {
  MAXIMUM_CONNECTION_COUNT: 150,
  MINIMUM_CONNECTION_COUNT: 0,
  MAXIMUM_IDLE_TIME: 10000,
  MAXIMUM_WAITING_TIME: 30000,
  INVALID_DATE: 'Invalid Date',
};

module.exports = DATABASE;
