const GAME_RULE = {
  INITIAL_ROUND: 1,
  MIN_PLAYER_COUNT: 2,
  MAX_PLAYER_COUNT: 4,
  ONE_SET_SECONDS: 30,
  MAX_ROUND_NUMBER: 1,
  MAX_QUIZ_SELECTION_WAITING_SECONDS: 10,
  MAX_PEER_CONNECTION_WAITING_SECONDS: 10,
  QUIZ_CANDIDATES_COUNT: 3,
  SECONDS_BETWEEN_SETS: 5,
  SECONDS_AFTER_GAME_END: 10,
  MAX_CHAT_LENGTH: 40,
  NICKNAME_LENGTH: 8,
  DEFAULT_QUIZ: '',
};

module.exports = GAME_RULE;
